### ISSUE TITLE
Can't get tests passed on Alpine Linux

### ISSUE THREAD

**Issue by DDoSolitary** [gregvirgin/libcork#123]
`shared-test-core` and `embedded-test-core` complains: Unexpectedly formatted local time (got " 1992-03-07 20:26:40 ", expected " 1992-03-07 12:26:40 ". Any ideas please?

**Comment by rogers0** [comment]
you may try debian packaged version
 - https://tracker.debian.org/pkg/libcork

which contains a few patches:
 - https://sources.debian.net/src/libcork/0.15.0%2Bds-11/debian/patches/

**Comment by DDoSolitary** [comment]
Thanks, I'll try the patches.

**Comment by DDoSolitary** [comment]
It turns out that the reason is that I didn't install the tzdata package...
